import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    'playwright-report',
    'test-results',
    'e2e/.auth',
    // Throwaway multi-model QA-sweep harness specs. Generated by Codex /
    // Opus QA passes, intentionally untracked, contain best-effort empty
    // catches and unused imports that the harness sometimes drops in.
    // Excluded from lint so the gate signal stays meaningful.
    'e2e/_qa-*.spec.ts',
    'qa-config.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
])
